const colors = {
  green: "#043927",
  greenHover: "#0a4a32",
  gold: "#C4B000",
  goldDark: "#6B5F00",
  goldBg: "rgba(196, 176, 0, 0.15)",

  bg: "#043927",          // page background — Sac State green
  surface: "#FFFFFF",     // cards, navbar
  surfaceMuted: "#F4F3EE",
  onGreen: "#FFFFFF",            // text on green background
  onGreenMuted: "rgba(255,255,255,0.78)",

  textPrimary: "#1A1A1A",
  textSecondary: "#6B6B6B",
  textTertiary: "#9A9A9A",

  border: "rgba(0, 0, 0, 0.08)",
  borderHover: "rgba(0, 0, 0, 0.16)",

  danger: "#C2410C",
  dangerBg: "#FEF2EC",
  warning: "#B45309",
  success: "#0A6E48",
  successBg: "#E8F5EE",
};

const radius = {
  sm: "6px",
  md: "8px",
  lg: "12px",
  pill: "999px",
};

const fonts = {
  body: "'Poppins', system-ui, -apple-system, 'Segoe UI', sans-serif",
};

const styles = {
  body: {
    margin: 0,
    fontFamily: fonts.body,
    backgroundColor: colors.bg,
    minHeight: "100vh",
    color: colors.textPrimary,
  },
  page: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    backgroundColor: colors.bg,
  },

  navbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 28px",
    backgroundColor: colors.surface,
    borderBottom: `1px solid ${colors.border}`,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "14px",
    fontWeight: 500,
    color: colors.textPrimary,
    cursor: "pointer",
    userSelect: "none",
  },
  brandLogo: {
    width: "30px",
    height: "30px",
    borderRadius: "7px",
    backgroundColor: colors.green,
    color: colors.gold,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
    fontSize: "14px",
  },
  navLinks: {
    display: "flex",
    alignItems: "center",
    gap: "26px",
    fontSize: "13px",
    color: colors.textSecondary,
  },
  navLink: {
    color: colors.textSecondary,
    cursor: "pointer",
    textDecoration: "none",
  },
  navIcons: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: colors.textSecondary,
  },
  iconBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "34px",
    height: "34px",
    borderRadius: radius.md,
    cursor: "pointer",
    color: colors.textSecondary,
    background: "transparent",
    border: "none",
    fontFamily: fonts.body,
  },
  signInBtn: {
    backgroundColor: colors.green,
    color: "white",
    fontSize: "13px",
    fontWeight: 500,
    padding: "8px 16px",
    borderRadius: radius.pill,
    border: "none",
    cursor: "pointer",
    fontFamily: fonts.body,
  },

  hero: {
    padding: "36px 32px",
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    margin: "24px 28px 0",
  },
  pill: {
    display: "inline-block",
    fontSize: "11px",
    padding: "4px 10px",
    borderRadius: radius.pill,
    backgroundColor: colors.goldBg,
    color: colors.goldDark,
    fontWeight: 500,
    letterSpacing: "0.4px",
    textTransform: "uppercase",
  },
  heroTitle: {
    fontSize: "32px",
    fontWeight: 600,
    margin: "14px 0 10px",
    color: colors.textPrimary,
    lineHeight: 1.2,
    maxWidth: "640px",
  },
  heroSub: {
    fontSize: "15px",
    color: colors.textSecondary,
    maxWidth: "520px",
    lineHeight: 1.6,
    margin: "0 0 24px",
  },
  heroBtnRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },

  primaryBtn: {
    backgroundColor: colors.green,
    color: "white",
    border: "none",
    borderRadius: radius.md,
    padding: "11px 20px",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.body,
  },
  primaryBtnFull: {
    width: "100%",
    backgroundColor: colors.green,
    color: "white",
    border: "none",
    height: "44px",
    borderRadius: radius.md,
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.body,
  },
  ghostBtn: {
    backgroundColor: "transparent",
    color: colors.textPrimary,
    border: `1px solid ${colors.borderHover}`,
    borderRadius: radius.md,
    padding: "10px 18px",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.body,
  },
  dangerGhostBtn: {
    backgroundColor: "transparent",
    color: colors.danger,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    padding: "10px 16px",
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.body,
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },

  section: {
    padding: "28px",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: 500,
    margin: 0,
    color: colors.onGreen,
  },
  sectionLink: {
    fontSize: "13px",
    color: colors.onGreenMuted,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },

  eventList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  eventCard: {
    display: "flex",
    gap: "16px",
    padding: "16px",
    borderRadius: radius.md,
    alignItems: "center",
    backgroundColor: colors.surface,
  },
  eventDate: {
    width: "60px",
    flexShrink: 0,
    textAlign: "center",
    padding: "8px 0",
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
  },
  eventMonth: {
    fontSize: "11px",
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    fontWeight: 500,
  },
  eventDay: {
    fontSize: "20px",
    fontWeight: 600,
    color: colors.textPrimary,
    marginTop: "2px",
  },
  eventBody: {
    flex: 1,
    minWidth: 0,
  },
  eventTitle: {
    fontSize: "15px",
    fontWeight: 500,
    color: colors.textPrimary,
    margin: "0 0 4px",
  },
  eventMeta: {
    fontSize: "12px",
    color: colors.textSecondary,
    display: "flex",
    alignItems: "center",
    gap: "14px",
    flexWrap: "wrap",
  },
  eventMetaItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
  },
  eventBtn: {
    backgroundColor: "transparent",
    color: colors.textPrimary,
    border: `1px solid ${colors.borderHover}`,
    borderRadius: radius.md,
    padding: "7px 14px",
    fontSize: "12px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.body,
    flexShrink: 0,
  },

  authBody: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: "56px 20px 80px",
    backgroundColor: colors.bg,
  },
  authContainer: {
    width: "100%",
    maxWidth: "420px",
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    padding: "36px 32px",
  },
  authHeader: {
    textAlign: "center",
    marginBottom: "32px",
  },
  authLogo: {
    width: "48px",
    height: "48px",
    margin: "0 auto 14px",
    backgroundColor: colors.green,
    color: colors.gold,
    borderRadius: "11px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "20px",
    fontWeight: 600,
  },
  authTitle: {
    fontSize: "22px",
    fontWeight: 600,
    margin: "0 0 6px",
    color: colors.textPrimary,
  },
  authSubtitle: {
    fontSize: "13px",
    color: colors.textSecondary,
    margin: 0,
  },

  formGroup: {
    marginBottom: "16px",
  },
  labelRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: "6px",
  },
  label: {
    fontSize: "12px",
    color: colors.textSecondary,
    fontWeight: 500,
    display: "block",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    height: "42px",
    border: `1px solid ${colors.borderHover}`,
    borderRadius: radius.md,
    padding: "0 14px",
    fontSize: "14px",
    color: colors.textPrimary,
    backgroundColor: colors.surface,
    boxSizing: "border-box",
    fontFamily: fonts.body,
    outline: "none",
  },
  inputError: {
    borderColor: colors.danger,
  },
  passwordWrap: {
    position: "relative",
  },
  passwordToggle: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "12px",
    color: colors.textSecondary,
    padding: "4px",
    fontFamily: fonts.body,
  },
  errorText: {
    color: colors.danger,
    fontSize: "12px",
    marginTop: "6px",
  },
  forgotLink: {
    fontSize: "12px",
    color: colors.green,
    fontWeight: 500,
    cursor: "pointer",
  },
  rememberRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: colors.textSecondary,
    margin: "16px 0 20px",
    cursor: "pointer",
    userSelect: "none",
  },
  authFooter: {
    textAlign: "center",
    fontSize: "13px",
    color: colors.textSecondary,
    margin: "20px 0 0",
  },
  authLink: {
    color: colors.green,
    fontWeight: 500,
    cursor: "pointer",
  },
  successBox: {
    backgroundColor: colors.successBg,
    color: colors.success,
    border: "1px solid rgba(10, 110, 72, 0.2)",
    padding: "10px 14px",
    borderRadius: radius.md,
    fontSize: "13px",
    textAlign: "center",
    marginTop: "16px",
  },

  strengthTrack: {
    height: "4px",
    borderRadius: "4px",
    backgroundColor: colors.surfaceMuted,
    marginTop: "8px",
    overflow: "hidden",
  },
  strengthFill: {
    height: "100%",
  },
  strengthLabel: {
    fontSize: "11px",
    marginTop: "5px",
    fontWeight: 500,
  },

  profileBody: {
    flex: 1,
    backgroundColor: colors.bg,
    padding: "40px 28px 80px",
  },
  profileContainer: {
    maxWidth: "640px",
    margin: "0 auto",
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    padding: "32px",
  },
  profileHeader: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
    marginBottom: "28px",
  },
  avatar: {
    width: "68px",
    height: "68px",
    borderRadius: "50%",
    backgroundColor: colors.green,
    color: colors.gold,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "22px",
    fontWeight: 600,
    flexShrink: 0,
  },
  avatarSmall: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: colors.green,
    color: colors.gold,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: 600,
  },
  profileName: {
    fontSize: "22px",
    fontWeight: 600,
    margin: 0,
    color: colors.textPrimary,
  },
  profileMeta: {
    fontSize: "13px",
    color: colors.textSecondary,
    margin: "3px 0 0",
  },
  sectionLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: "0.7px",
    margin: "0 0 14px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "16px",
  },
  passwordRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "42px",
    border: `1px solid ${colors.borderHover}`,
    borderRadius: radius.md,
    padding: "0 14px",
    backgroundColor: colors.surface,
  },
  passwordRowText: {
    fontSize: "14px",
    color: colors.textSecondary,
  },
  profileFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "24px",
    marginTop: "28px",
    borderTop: `1px solid ${colors.border}`,
    flexWrap: "wrap",
    gap: "10px",
  },
  profileFooterRight: {
    display: "flex",
    gap: "10px",
  },

  confirmContainer: {
    maxWidth: "420px",
    margin: "80px auto 0",
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    padding: "48px 32px",
    textAlign: "center",
  },
  confirmIcon: {
    width: "56px",
    height: "56px",
    margin: "0 auto 18px",
    borderRadius: "50%",
    backgroundColor: colors.successBg,
    color: colors.success,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmTitle: {
    fontSize: "20px",
    fontWeight: 600,
    margin: "0 0 8px",
    color: colors.textPrimary,
  },
  confirmText: {
    fontSize: "14px",
    color: colors.textSecondary,
    margin: "0 0 28px",
    lineHeight: 1.6,
  },
  confirmBtnRow: {
    display: "flex",
    gap: "10px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
};

export default styles;
export { colors, radius, fonts };
